#!/bin/bash

echo -e "Please enter the desired amount of records to compare to in proximity measurements: "
read p
echo "Kicking off our Python program to calculate predictions based on $p nearest neighbors."

python assignment2.py $p